version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BASE_URL=http://localhost:8000  # Ensure it's set like this
    networks:
      - app-network  # Both services should be on the same network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network  # Both services should be on the same network


networks:
  app-network:
    driver: bridge  # Use bridge network for communication between containers
